# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_29bfa304cdc84cabaa26f97a09faf314 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5337b8b717f146ffb7b582757165fb8a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_29bfa304cdc84cabaa26f97a09faf314 }}/service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9cc059ed8a6a41a9ac0e71cda23b0cb9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_29bfa304cdc84cabaa26f97a09faf314 }}/service:${{ github.sha }}'